services:
  order-service:
    build: ./order-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/orderdb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/paymentdb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka
    networks:
      - microservices-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - microservices-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
